### ISSUE TITLE
_type_ 'v' not supported

### ISSUE THREAD

**Issue by uriva** [google/pytype#105] opened 2018-07-29 06:16 UTC
I'm getting the following error for tensorflow:

`import tensorflow`

> /home/me/.local/lib/python3.6/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
>   "You should import from ipykernel or jupyter_client instead.", ShimWarning)
> CRITICAL Cannot parse input files:
> _type_ 'v' not supported
> 

Perhaps has something to do with Cython?

I'm on Python 3.6.5

**Comment by rchen152** [comment] 2018-08-07 19:34
This looks like a warning issued by the Python interpreter we use to compile source code to bytecode. You can probably ignore it, but we should check if it's possible to not show it.

**Comment by uriva** [comment] 2018-08-08 09:16
I'm pretty sure this interferes with pytype, as I added to a file the following code:

```
def bla(text: Text):
    pass

bla(1)
```
And pytype did not report anything.

**Comment by uriva** [comment] 2018-08-28 09:57
Friendly ping
(even if this is not to be fixed, would be good to understand if the issue is reproducible)

**Comment by rchen152** [comment] 2018-09-07 22:47
Sorry for the late reply; I was on vacation. Based on the similar https://github.com/google/pytype/issues/133, it seems like this is actually a bug in [importlab](https://github.com/google/importlab), the library pytype uses to get dependency information. That bug was already fixed, so the next importlab release should solve this issue :)

**Comment by rchen152** [comment] 2018-09-08 00:29
importlab-0.3.0 was released, which should have fixed this bug; please reopen if you're still seeing it.

**Comment by AnObfuscator** [comment] 2018-09-09 23:51
I'm having this same issue, too.

**Comment by rchen152** [comment] 2018-09-10 17:07
Oops, looks like I closed the issue too early. Unfortunately, since importlab runs before pytype, making pytype ignore the import won't solve this problem (but for future reference, you can tell pytype to do so by putting `# type: ignore` at the end of the import line).

**Comment by rchen152** [comment] 2018-09-27 01:06
It doesn't seem like there's anything else to do here - the issue needs to be fixed in importlab (and isn't reproducible in a virtualenv?).

**Closed by rchen152** 2018-09-27 01:06 UTC
Labels: bug
