### ISSUE TITLE
Imports Failing in Virtualenv

### ISSUE THREAD

**Issue by goakley** [google/pytype#87] opened 2018-05-22 23:25 UTC
When running `pytype` and `pytype-all` while in a virtualenv, the tool frequently fails on importing certain packages that have been installed via `pip`.

The following script reproduces the problem by installing `boto3` and running pytype on a file that merely imports `boto3`:
```
#!/bin/bash
cd $(mktemp -d)
virtualenv -p python2.7 env
source env/bin/activate
pip install boto3 pytype
echo "import boto3" > py.py
pytype py.py
rm -r $(pwd)
```

The core of that script, `pytype py.py`, will provide the following output:
```
File "py.py", line 1, in <module>: Can't find module 'boto3'. [import-error]
```

Merely running `python py.py` will import the module with no errors, so the problem appears to be specific to `pytype`.

**Comment by martindemello** [comment] 2018-05-22 23:29
right, the problem is not with virtualenv, it's that pytype-all doesn't currently support dependencies installed via pip. we're working on that; it should be fixed pretty soon.

**Closed as completed** 2018-06-04 23:25 UTC
