### ISSUE TITLE
Pytype crashes when analysing `with open(..) as f` in python3.5

### ISSUE THREAD

**Issue by fyquah95** [google/pytype#43] opened 2017-01-23 00:43 UTC
Pytype crashed on the following code snippet when run with `pytype test.py -V 3.5`

```
with open("a.txt", "w") as f:
    f.write("Hello")
```

```
Traceback (most recent call last):
  File "/usr/local/bin/pytype", line 263, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/usr/local/bin/pytype", line 210, in main
    return _run_pytype(options)
  File "/usr/local/bin/pytype", line 251, in _run_pytype
    errors_csv_file=errors_csv_file)
  File "/usr/local/bin/pytype", line 139, in process_one_file
    options=options)
  File "/usr/local/bin/pytype", line 51, in check_pyi
    cache_unknowns=options.cache_unknowns)
  File "/usr/local/lib/python2.7/site-packages/pytype/infer.py", line 640, in check_types
    py_src, py_filename, init_maximum_depth, run_builtins)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 580, in run_program
    code = self.compile_src(src, filename=filename)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 532, in compile_src
    return blocks.process_code(code)
  File "/usr/local/lib/python2.7/site-packages/pytype/blocks.py", line 220, in process_code
    return pyc.visit(code, OrderCodeVisitor())
  File "/usr/local/lib/python2.7/site-packages/pytype/pyc/pyc.py", line 192, in visit
    return visitor.visit_code(c)
  File "/usr/local/lib/python2.7/site-packages/pytype/blocks.py", line 216, in visit_code
    return order_code(code)
  File "/usr/local/lib/python2.7/site-packages/pytype/blocks.py", line 206, in order_code
    bytecodes = opcodes.dis_code(code)
  File "/usr/local/lib/python2.7/site-packages/pytype/pyc/opcodes.py", line 1045, in dis_code
    co_firstlineno=code.co_firstlineno)
  File "/usr/local/lib/python2.7/site-packages/pytype/pyc/opcodes.py", line 1033, in dis
    return _dis(data, mapping, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pytype/pyc/opcodes.py", line 999, in _dis
    cls = mapping[opcode]
KeyError: 82
```

**Comment by matthiaskramm** [comment] 2017-01-24 14:34
Hey Fu Yong,

long time no see! :)
Thanks for the bug report. We'll take a look. We're still a bit behind on Python 3 support.

Matthias

**Comment by martindemello** [comment] 2017-04-24 23:18
duplicate of #38

**Closed by martindemello** 2017-04-24 23:18 UTC
