### ISSUE TITLE
Pytype does not work with Python distributions like Anaconda

### ISSUE THREAD

**Issue by jjedele** [google/pytype#228] opened 2019-01-17 15:18 UTC
Commonly used Python distributions like Anaconda modify the version string emitted by `python -V` in a way that break the current parsing logic in _utils.py_.

Example:

```
$ python -V
Python 3.6.4 :: Anaconda custom (64-bit)

$ pytype src/add.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/Users/jeff/Downloads/coala-tutorial/pytype_output'
[1/1] pytype-single --imports_info /Users/jeff/Downloads/coala-tutorial/pyt...-annotated --nofail --quick /Users/jeff/Downloads/coala-tutorial/src/add.py
FAILED: /Users/jeff/Downloads/coala-tutorial/pytype_output/pyi/add.pyi
pytype-single --imports_info /Users/jeff/Downloads/coala-tutorial/pytype_output/imports/add.imports --module-name add -V 3.6 -o /Users/jeff/Downloads/coala-tutorial/pytype_output/pyi/add.pyi --analyze-annotated --nofail --quick /Users/jeff/Downloads/coala-tutorial/src/add.py
Traceback (most recent call last):
  File "/Users/jeff/anaconda/bin/pytype-single", line 11, in <module>
    sys.exit(main())
  File "/Users/jeff/anaconda3/lib/python3.6/site-packages/pytype/main.py", line 66, in main
    options = config.Options(sys.argv[1:])
  File "/Users/jeff/anaconda3/lib/python3.6/site-packages/pytype/config.py", line 48, in __init__
    Postprocessor(names, options, self).process()
  File "/Users/jeff/anaconda3/lib/python3.6/site-packages/pytype/config.py", line 357, in process
    node.processor(value)
  File "/Users/jeff/anaconda3/lib/python3.6/site-packages/pytype/config.py", line 481, in _store_python_exe
    python_exe_version = utils.get_python_exe_version(python_exe)
  File "/Users/jeff/anaconda3/lib/python3.6/site-packages/pytype/utils.py", line 158, in get_python_exe_version
    return split_version(python_exe_version.split()[-1].rsplit(".", 1)[0])
  File "/Users/jeff/anaconda3/lib/python3.6/site-packages/pytype/utils.py", line 47, in split_version
    return tuple(map(int, version_string.split(".")))
ValueError: invalid literal for int() with base 10: '(64-bit)'
ninja: build stopped: subcommand failed.
```

**Comment by rchen152** [comment] 2019-01-23 19:46
The fix for this was released in pytype 2019.01.18. Thanks @jjedele, and please let me know if the issue isn't resolved.

**Closed by rchen152** 2019-01-23 19:46 UTC
