### ISSUE TITLE
pytype crashed due to comparison between str and None

### ISSUE THREAD

**Issue by dumblob** [google/pytype#384] opened 2019-08-13 17:11 UTC
This is actually the root issue and while searching for the minimal reproducer I've encountered also https://github.com/google/pytype/issues/383 .
```python
def f( t ):
  return t.strftime( myfmt )

class C:
  def m( x: str ):
    return True
```
```
Computing dependencies
Analyzing 4 sources with 0 local dependencies
ninja: Entering directory `/home/user/app/.pytype'
[1/1] check main
FAILED: /home/user/app/.pytype/pyi/main.pyi 
pytype-single --imports_info /home/user/app/.pytype/imports/main.imports --module-name main -V 3.7 -o /home/user/app/.pytype/pyi/main.pyi --analyze-annotated --nofail --quick /home/user/app/main.py
Traceback (most recent call last):
  File "/home/user/app/env00/bin/pytype-single", line 10, in <module>
    sys.exit(main())
  File "/home/user/app/env00/lib/python3.7/site-packages/pytype/main.py", line 88, in main
    return _run_pytype(options)
  File "/home/user/app/env00/lib/python3.7/site-packages/pytype/main.py", line 99, in _run_pytype
    return io.process_one_file(options)
  File "/home/user/app/env00/lib/python3.7/site-packages/pytype/io.py", line 199, in process_one_file
    exit_status = handle_errors(errorlog, options)
  File "/home/user/app/env00/lib/python3.7/site-packages/pytype/io.py", line 254, in handle_errors
    errorlog.print_to_stderr()
  File "/home/user/app/env00/lib/python3.7/site-packages/pytype/errors.py", line 442, in print_to_stderr
    self.print_to_file(sys.stderr)
  File "/home/user/app/env00/lib/python3.7/site-packages/pytype/errors.py", line 403, in print_to_file
    for error in self.unique_sorted_errors():
  File "/home/user/app/env00/lib/python3.7/site-packages/pytype/errors.py", line 409, in unique_sorted_errors
    for error in self._sorted_errors():
  File "/home/user/app/env00/lib/python3.7/site-packages/pytype/errors.py", line 439, in _sorted_errors
    return sorted(self._errors, key=lambda x: (x.filename, x.lineno))
TypeError: '<' not supported between instances of 'str' and 'NoneType'
ninja: build stopped: subcommand failed.
```

It would be also nice in such cases to maybe print at least line numbers where pytype was lastly doing its analysis as this would allow for significantly faster search for the culprit.

**Comment by martindemello** [comment] 2019-08-13 19:11
this is a pytype bug rather than a bad error message :( the problem is that it crashed in the error reporting stage, so that pytype-single threw up a stack trace rather than an error message.

**Comment by domandinho** [comment] 2019-09-15 19:25
Suggested fixes for error from this issue:

https://github.com/google/pytype/pull/406
https://github.com/google/pytype/pull/412

**Comment by rchen152** [comment] 2019-09-18 06:45
The fix for this has been released. Thanks @domandinho!

**Closed by rchen152** 2019-09-18 06:45 UTC
Labels: Pytype Fixit, bug
