### ISSUE TITLE
Pytype error that there is no pyi file for a subpackage

### ISSUE THREAD

**Issue by MarkCBell** [google/pytype#320] opened 2019-05-19 14:40 UTC
I have a package `foo` with subpackage `foo.bar` the directory structure is:

`foo/__init__.py`
```
import foo.bar
```

`foo/bar/__init__.py`
```
from .a import A
```

`foo/bar/a.py`
```
import foo

class A():
    def a(self):  # Return a new instance of A by its full name.
        return foo.bar.A()
```

So within Python I can do:
```
>>> import foo
>>> a = foo.bar.A()
>>> a
<foo.bar.a.A object at 0x100ac4c88>
>>> a.a()
<foo.bar.a.A object at 0x100ac9ac8>
```

However if I run `pytype foo/` I get the following error:
```
File ".../foo/bar/a.py", line 5, in b: Couldn't import pyi for 'foo.bar' [pyi-error]
  No a.A in module foo.bar, referenced from 'foo.bar'
```

It looks to me like pytype was expecting a `foo/bar.pyi` to have been created. However there is no such file in `.pytype/pyi/` although there is a `.pytype/pyi/foo/bar/__init__.pyi` as I would expect since `bar` is a subpackage. Of course if A.a() just returned A() then this would not be an issue but in the full version of my code it returns some other class from within a different subpackage and so this is the only way to avoid circular references.

This is under:
pytype --version: 2019.05.15
python --version: Python 3.7.0

**Comment by rchen152** [comment] 2019-05-20 17:04
What I think is happening is that when pytype analyzes `foo/bar/a.py`, it tries to load the previously generated `foo/bar/__init__.pyi`, which then tries to look up a pyi file for `foo/bar/a.pyi`, which doesn't exist yet. We usually resolve this sort of import cycle by running pytype over the cycle twice, but I guess importlab (https://github.com/google/importlab) doesn't recognize this as a cycle.

**Comment by rchen152** [comment] 2021-01-11 09:29
This seems to have the same root cause as https://github.com/google/pytype/issues/760. Closing this issue in favor of that one, since the comments on the latter contain more information about the problem.

**Closed by rchen152** 2021-01-11 09:29 UTC
Labels: bug
