### ISSUE TITLE
Error importing pyi for jinja2.

### ISSUE THREAD

**Issue by dseomn** [google/pytype#232] opened 2019-01-21 15:55 UTC
Hi,

I just tried to run pytype for the first time on a project, and got this error:

https://travis-ci.org/dseomn/dotfiles/jobs/482477906
```
$ pytype .
Computing dependencies
Analyzing 14 sources with 0 local dependencies
ninja: Entering directory `/home/travis/build/dseomn/dotfiles/.local/lib/python3/site-packages/pytype_output'
[4/14] pytype-single --imports_info /h.../site-packages/dconf_load_yaml/main.py
FAILED: /home/travis/build/dseomn/dotfiles/.local/lib/python3/site-packages/pytype_output/pyi/snipphthalate/comment.pyi 
pytype-single --imports_info /home/travis/build/dseomn/dotfiles/.local/lib/python3/site-packages/pytype_output/imports/snipphthalate.comment.imports --module-name snipphthalate.comment -V 3.5 -o /home/travis/build/dseomn/dotfiles/.local/lib/python3/site-packages/pytype_output/pyi/snipphthalate/comment.pyi --analyze-annotated --nofail --quick /home/travis/build/dseomn/dotfiles/.local/lib/python3/site-packages/snipphthalate/comment.py
File "/home/travis/build/dseomn/dotfiles/.local/lib/python3/site-packages/snipphthalate/comment.py", line 16, in <module>: Couldn't import pyi for 'jinja2' [pyi-error]
  ParseError: Duplicate top-level identifier(s): escape_silent, escape, soft_unicode
For more details, see https://github.com/google/pytype/blob/master/docs/errors.md#pyi-error.
```

https://github.com/google/pytype/blob/master/docs/errors.md#pyi-error says to file a bug, so I am.

**Comment by rchen152** [comment] 2019-01-23 18:45
Thanks for the report! I reproduced this bug with:
```
echo "import jinja2" > foo.py
pytype foo.py
```
Looking at https://github.com/python/typeshed/blob/master/third_party/2and3/jinja2/utils.pyi, there are no duplicate definitions, so it's probably a bug in our parser.

In general, we're not catching these sorts of issues due to https://github.com/google/pytype/issues/171 =/

**Comment by rchen152** [comment] 2019-05-15 23:07
This is fixed by today's pytype release!

**Closed by rchen152** 2019-05-15 23:07 UTC
Labels: bug
