### ISSUE TITLE
AssertionError: Don't know how to match <class 'pytype.pytd.pytd.NamedType'> against <class 'pytype.pytd.pytd.Literal'>

### ISSUE THREAD

**Issue by maldil** [google/pytype#722] opened 2020-10-30 23:00 UTC
I came across the assertion error in https://github.com/google/pytype/blob/cf969bca963c56fabbf9cdc2ed39548c843979dc/pytype/pytd/type_match.py#L379

The error message is
```AssertionError: Don't know how to match <class 'pytype.pytd.pytd.NamedType'> against <class 'pytype.pytd.pytd.Literal'>```

The code that I was trying to resolve is as follows. 
```
def main():
    f = open("./file.txt", "r")
    for x in f:
        print(x)
    f.close()
```

I believe the error is self-explanatory. Does anybody have an idea about a fix? 

Pytype version = 2020.10.08

Thank you!

**Comment by rchen152** [comment] 2020-11-03 21:10
I'm having trouble reproducing this error. What I tried was:

1. Putting
```python
def main():
    f = open("./file.txt", "r")
    for x in f:
        print(x)
    f.close()
```
in a file called `foo.py`.
2. Installing pytype 2020.10.08 in a Python 3.8 virtualenv.
3. Running `pytype-single foo.py`.

Are you running pytype with any custom settings? Is there maybe surrounding code that is contributing to the error?

**Comment by maldil** [comment] 2020-11-04 08:18
Thank you for your attention.
I reproduced this error in a new python virtual environment again. 
The steps that I followed are as below. 

1. putting in a file named "foo.py"
```
def main():
    f = open("./file.txt", "r")
    for x in f:
        print(x)
    f.close()

if __name__ == "__main__":
    main()

```
2. Use following code after running `pytype filename`. 

```
    from pytype import config
    from pytype.tools.annotate_ast import annotate_ast
    def annotate(source, file_name):
        source = textwrap.dedent(source.lstrip('\n'))
        ast_factory = lambda unused_options: ast
        pytype_options = config.Options.create(python_version=(3, 7), nofail=True, protocols=True,
                                               imports_map=pytype_out_path + '/imports/' + file_name) 
        # pytype_out_path is the .pytype folder created from `pytype filename`

        module = annotate_ast.annotate_source(source, ast_factory, pytype_options)
        return module
    if __name__ == '__main__':
       with open("./foo.py", 'r') as f:
             src = f.read()
       annotate(src,foo.py)
```

3. assertion fired from the `module = annotate_ast.annotate_source(source, ast_factory, pytype_options)`.

**Comment by rchen152** [comment] 2020-11-05 04:10
Thanks for the additional information! I'll look into this tomorrow, time allowing.

**Comment by rchen152** [comment] 2020-11-05 21:10
Ah, I think I figured out how to reproduce, at least. Inference plus the `--protocols` flag triggers the error. If I do the steps from my previous comment but run `pytype-single foo.py --protocols -o -` in step 3, I get the AssertionError.

**Comment by rchen152** [comment] 2021-01-14 22:09
Closing this in favor of https://github.com/google/pytype/issues/802, since the latter has an attached PR (thanks!).

**Closed by rchen152** 2021-01-14 22:09 UTC
Labels: bug
