### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by jrenner** [google/pytype#25] opened 2016-06-06 14:57 UTC
I'm attempting to use pytype and it appears it doesn't support Python 3( complains about no StringIO module).  Any plans to support Python 3? or, perhaps add some documentation about which version of Python are supported.

**Comment by matthiaskramm** [comment] 2016-06-07 20:49
Yeah, you need Python 2.7 to run pytype. (It can analyze both Python 2 and 3, though)

I'll update the README.

**Comment by johnthagen** [comment] 2016-06-09 12:01
I'm genuinely interested to learn why you chose Python 2 only, is it so there is an alternative to `mypy` which requires Python 3?

I would suggest also updating `setup.py` by adding a trove `classifier`: 
```
Programming Language :: Python :: 2.7
```

**Comment by matthiaskramm** [comment] 2016-06-09 17:40
Historical reasons. We'll move to Python 3 at some point. For a while we had a codebase that would run under both 2 and 3, but since it can also *analyze* 2 and 3 (and there were version based if-blocks for both), things got too confusing.

A trove classifier is a good idea, I'll add that (and I'll also adjust `README.md`) and then close the bug.

**Comment by nedbat** [comment] 2018-02-05 12:18
FWIW: "It can analyze Python 3" is misleading: it fails with "invalid syntax [python-compiler-error]" if it encounters async or await keywords.

**Comment by matthiaskramm** [comment] 2018-02-05 14:27
This seems to work for me. Ned, did you pass `--python_version`?

**Comment by nedbat** [comment] 2018-02-05 15:00
Ah, sorry, my bad.  Too eager to see what would happen :)

**Comment by johnthagen** [comment] 2018-02-05 15:22
@matthiaskramm Curious in general what the plan is when Python 2 loses official support. Does Google plan to keep their Python 2-only projects running using something like [grumpy](https://github.com/google/grumpy)?

**Comment by matthiaskramm** [comment] 2018-02-05 15:31
@johnthagen: I can only offer my personal opinion. I think that in general, for companies running Python 2, the end-of-life date won't change much. You'll get your security patches from another source, but that's about it. It's not like the CPython interpreter just stops working, in 2020. :)

**Comment by johnthagen** [comment] 2018-02-05 16:16
@matthiaskramm Thanks for the explanation!

**Comment by kamahen** [comment] 2018-02-05 16:32
I get this error with -V3.6. (-V3.5 works, but gives me errors for `from . import` statements):

```
    File "/usr/local/lib/python2.7/dist-packages/pytype/pyc/opcodes.py", line 1231, in _dis
    op.arg = op.pretty_arg = offset_to_index[op.arg]
AssertionError: 250
Exception: KeyError
```

**Comment by martindemello** [comment] 2018-02-06 23:24
@kamahen could you add the code snippet that you got that assertion error for?

**Comment by martindemello** [comment] 2018-02-06 23:48
@kamahen sure, if the code is open source just point me to it and i'll investigate. i'm guessing it's a problem with how we read the new wordcode format in 3.6.

**Comment by kamahen** [comment] 2018-02-07 00:22
```
mkdir /tmp/somethingsomething
cd /tmp/somethingsomething
git clone https://github.com/kamahen/pykythe.git
make -C /tmp/somethingsomething/pykythe pytype
```
(please don't laugh at the code; it's very much a work-in-progress, done to try out some ideas in my spare time)

(If you leave off the `-P`, you can see other errors, and -V3.5 seems to expose some other issues)

Also, it'd be nice if you could tell me how to handle `from . import` ... the Makefile contains my best guess but it's wrong (BTW, there's a typo in `pytype --help` for `-P` -- it ought to be `.pyi` and not `.pytd`.

**Comment by martindemello** [comment] 2018-02-07 00:57
from . import does seem to be broken, thanks for the report!

**Comment by martindemello** [comment] 2018-02-07 01:33
here's the bytecode that's causing the crash:
````
            236 JUMP_IF_FALSE_OR_POP   250                                                                             
            238 LOAD_FAST                0 (node)                                                                      
            240 LOAD_ATTR                3 (children)                                                                  
            242 LOAD_CONST               8 (1)                                                                         
            244 BINARY_SUBSCR                                                                                          
            246 LOAD_GLOBAL              7 (SYMS_COMP_FOR)                                                             
            248 COMPARE_OP               2 (==)                                                                        
        >>  250 EXTENDED_ARG             1                                                                             
            252 POP_JUMP_IF_FALSE      292               
````

i did not realise you could jump to an `EXTENDED_ARG` (what does that even mean?!) and have not been storing them in the table. will push a fix, though i'm still mystified by the bytecode.

**Comment by matthiaskramm** [comment] 2018-02-07 14:34
It's not jumping to the `EXTENDED_ARG`, as such. The latter belongs to the next instruction, so it jumps to `POP_JUMP_IF_FALSE`. I've never seen a conditional jump branch directly to another conditional jump instruction before, though.

**Comment by kamahen** [comment] 2018-02-07 18:13
Looking at the disassembled code, it appears that conditional jump to conditional jump occurs with "and"; this one is different only in that it has a EXTENDED_ARG and uses JUMP_IF_FALSE_OR_POP instead of POP_JUMP_IF_FALSE (the latter is what's generated for Py3.5).

**Comment by martindemello** [comment] 2018-03-13 01:07
@kamahen if you update to head the crashes are fixed. `from . import` needs the file you are analysing to be within a package, so this fixes it:

````
-       -cd pykythe && pytype -V$(PYTYPE_V) -P $(PYTYPE_DIR) pod.py -o $(PYTYPE_DIR)/pod.pyi
+       pytype -V$(PYTYPE_V) -P $(PYTYPE_DIR) pykythe/pod.py -o $(PYTYPE_DIR)/pod.pyi
````

and similarly for the other files. `make pytype` still doesn't work because we don't support forward references in typevars; spefically this line is not going to work:
 ````
    _SelfType = TypeVar('_SelfType', bound='PlainOldData')
````

but hopefully that will give you enough to move forward.

**Comment by kamahen** [comment] 2018-03-13 03:32
Thank-you for fixing the `from . import` bug. This exposes a couple of other things (this is not an exhaustive list, but I haven't verified that the other ones aren't my fault).

It's not finding `typing.ChainMap`, which seems to be what I need for `mypy` (`collections.ChainMap[Text, Text]` gives a Python runtime error)  -- perhaps you're not processing this line correctly in `typeshed/stdlib/3/typing.pyi`: `if sys.version_info >= (3, 3): ChainMap = TypeAlias(object)`

I'm also getting this crash:
```
pytype -V3.6 -P /tmp/pykythe_pytype pykythe/typing_debug.py -o /tmp/pykythe_pytype/typing_debug.pyi
Traceback (most recent call last):
  File "../pytype/scripts/pytype", line 322, in <module>
    sys.exit(main(sys.argv) or 0)
  File "../pytype/scripts/pytype", line 288, in main
    return _run_pytype(options)
  File "../pytype/scripts/pytype", line 311, in _run_pytype
    options)
  File "../pytype/scripts/pytype", line 166, in process_one_file
    loader=loader)
  File "../pytype/scripts/pytype", line 111, in generate_pyi
    maximum_depth=1 if options.quick else 3)
  File "/usr/local/lib/python2.7/dist-packages/pytype/analyze.py", line 666, in infer_types
    loc, defs = tracer.run_program(src, filename, init_maximum_depth)
  File "/usr/local/lib/python2.7/dist-packages/pytype/vm.py", line 700, in run_program
    node, f_globals, _, _ = self.run_bytecode(node, code)
  File "/usr/local/lib/python2.7/dist-packages/pytype/vm.py", line 668, in run_bytecode
    node, return_var = self.run_frame(frame, node)
  File "/usr/local/lib/python2.7/dist-packages/pytype/vm.py", line 298, in run_frame
    state = self.run_instruction(op, state)
  File "/usr/local/lib/python2.7/dist-packages/pytype/vm.py", line 260, in run_instruction
    state = bytecode_fn(state, op)
  File "/usr/local/lib/python2.7/dist-packages/pytype/vm.py", line 2258, in byte_MAKE_FUNCTION
    get_args(state, op.arg))
  File "/usr/local/lib/python2.7/dist-packages/pytype/vm.py", line 2174, in _get_extra_function_args_3_6
    annot[k] = abstract.get_atomic_value(annot[k])
  File "/usr/local/lib/python2.7/dist-packages/pytype/abstract.py", line 69, in get_atomic_value
    % (name, variable, [a.data for a in variable.bindings]))
AssertionError: Cannot get atomic value <any> from variable. <Variable v451: 2 choices> [ParameterizedClass(cls=PyTDClass(type) params={'_T': TypeParameter('_T', constraints=(), bound=None)}), unsolveable]
Exception: ConversionError
File: pykythe/typing_debug.py
```

The contents of `pykythe/typing_debug.py` is:
```
"""Variants from the typing module, for debugging."""

# TODO: remove this when no longer needed.

from typing import Any, Sequence, Type, Tuple, TypeVar, Union

# This definition of `cast` is the same as typing.cast, except it
# verifies the type:
# TODO: replace by typing.cast

_T = TypeVar('_T')


def cast(typ: Type[_T], val: Any) -> _T:
    assert isinstance(val, typ), (typ, val)
    return val


def assert_all_isinstance(
        typ: Union[Type, Tuple[Type, ...]], val: Sequence[Any]) -> None:
    assert all(isinstance(v, typ) for v in val), val
```

**Comment by martindemello** [comment] 2018-03-13 23:51
thanks for all the bug reports! typing_debug crash fixed now.

**Comment by kamahen** [comment] 2018-03-14 00:33
I'm still having problems with imports.

```
$ /usr/local/bin/pytype -V3.6 -P /tmp/pykythe_pytype pykythe/ast_fqn.py -o /tmp/pykythe_pytype/ast_fqn.pyi
File "pykythe/ast_fqn.py", line 35, in <module>: Can't find module ''. [import-error]
```

If I instead do a `cd` into the source directory, the import works (using the generated `.pyi` file generated by `pytype`) but it doesn't like what was generated:
```
$ cd pykythe && /usr/local/bin/pytype -V3.6 -P /tmp/pykythe_pytype ast_cooked.py -o /tmp/pykythe_pytype/ast_cooked.pyi
File "ast_cooked.py", line 19, in <module>: Couldn't import pyi for '.ast_fqn' [pyi-error]
    File: "/tmp/pykythe_pytype/ast_fqn.pyi", line 1
      import .pod
             ^
  ParseError: syntax error, unexpected '.', expecting NAME
```

It's not easy to give you source code right now ... if you can't easily reproduce this, I'll probably have something reproducible in a few days.

**Comment by martindemello** [comment] 2018-03-14 19:08
can't reproduce this with latest head.
````
(.pytype) mdemello@mdemello-linux (master) ~/github/pykythe
$ pytype -V3.6  pykythe/ast_fqn.py -o - | head -3
import pykythe.pod
import typing
from typing import Sequence
````

**Comment by kamahen** [comment] 2018-03-14 22:37
@martindemello - The problem isn't with the direct import but with an indirect import via a `.pyi` file.

It'll take me a bit of work to create a repro, if you need one. This is the error when pytype tries to process (via import) a generated `.pyi` file:
```
      import .pod
             ^
  ParseError: syntax error, unexpected '.', expecting NAME
```

There also seems to be an import problem (for `.pyi` files) if I do `pytype -P /tmp/pytype_gen somedir/foo.py`, which goes away if I do `cd somedir && pytype -P /tmp/pytype_gen foo.py` ... the error message from pytype isn't very informative so I don't know what file it's looking for and not finding.

**Comment by martindemello** [comment] 2018-03-14 22:45
i think the problem is that you're processing `pykythe/ast_fqn.py` but generating the pyi into `topdir/ast_fqn.pyi` rather than `topdir/pykythe/ast_fqn.pyi`, so it is no longer in the `pykythe` package. relative imports require the files to be within a package directory.

**Comment by kamahen** [comment] 2018-03-14 23:17
@martindemello Yes, that's it. 
So, the renaming `import` problem is that your parser can't handle `import .foo` (which I no longer need because I don't `cd` into the source directory any more). 
Thanks!

**Comment by kamahen** [comment] 2018-03-15 04:49
Or maybe the solution is to output `from . import foo` to the `.pyi` file instead of `import .foo` (the latter is illegal Python — as far as I can tell, `from . import foo` has the semantics you expect for `import .foo`).

**Comment by martindemello** [comment] 2018-03-15 18:11
@kamahen another thing to try if pytype appears to be getting confused about relative imports is to pass an explicit --module_name argument for the module corresponding to the file you're analysing, so we can figure out what package you're importing relative to.

**Comment by MohamedAlFahim** [comment] 2018-05-20 21:34
Using the six library or creating an "experimental" branch for Python 3 would be a good idea.

**Comment by martindemello** [comment] 2018-05-22 00:47
@MohamedAlFahim what is missing in the shipping version of six? we haven't had any problems using it in the pytype codebase - that's how we achieve 2-and-3 compatibility right now, in fact.

**Comment by rchen152** [comment] 2018-09-26 22:52
Closing because we have Python 3 support now (both host and target) - specific issues with that support should get their own bugs.

**Closed by rchen152** 2018-09-26 22:52 UTC
