### ISSUE TITLE
`annotation-type-mismatch` reports false positive

### ISSUE THREAD

**Issue by cihati** [google/pytype#640] opened 2020-08-05 19:09 UTC
```
..... pytype.single --disable pyi-error --imports_info MYFILENAME--module-name backend.tools.ml.service -V 3.7 -o MYFILENAME.pyi --analyze-annotated --check-attribute-types --check-container-types --check-parameter-types --nofail --quick MYFILENAME
         File "MYFILENAME", line 61, in MLModelService: Type annotation for overwrite does not match type of assignment [annotation-type-mismatch]
           Annotation: bool
           Assignment: int
```

(redacted full path to `MYFILENAME`)

I have `check_parameter_types=True`

Line 61:

```
    def store(self, model_definition: ModelDefinition, model_object: Model, overwrite: bool = True) -> bool:
```

I think this is a bug by pytype (I'm using 2020.07.30 and Python 3.7.7)

**Comment by rchen152** [comment] 2020-08-06 01:06
I'm not able to produce this error by running pytype --check-parameter-types on a file containing just a single function with `overwrite: bool = True` as its parameter. Could you post a minimal repro? (Or, if you feel comfortable pointing me to the original code, I can take a look and see if I can figure out what's going on.)

**Comment by cihati** [comment] 2020-08-06 11:50
Thanks for the swift reply @rchen152 

When I add

```
class Repro:
    def store2(self, overwrite: bool = True) -> bool:
        return False
```

to the file (alongside existing classes), I can still observe the error:

```
/Users/foo/envs/backend/bin/python3 -m pytype.single --disable pyi-error --imports_info /Users/foo/somefolders/backend.tools.ml.service.imports --module-name backend.tools.ml.service -V 3.7 -o /Users/foo/somefolders/.pytype/pyi/xyz/service.pyi --analyze-annotated --check-attribute-types --check-container-types --check-parameter-types --check-variable-types --nofail --quick /Users/foo/someotherfolders/service.py
File "/Users/foo/someotherfolders/service.py", line 51, in Repro: Type annotation for overwrite does not match type of assignment [annotation-type-mismatch]
  Annotation: bool
  Assignment: int
```

If I create a new python file foo.py with that minimal class code I put above, and run `pytype --config=pytype.cfg foo.py` then pytype does not complain. I also searched for the string `overwrite` in the codebase (to see if there's a weird clash or smt) but it's not used elsewhere.

**Comment by rchen152** [comment] 2020-08-06 19:29
How should we proceed with this issue then? I'm still lacking a way to reproduce/debug what you're seeing.

**Comment by rchen152** [comment] 2020-08-11 18:47
Hi @cihati! I'm going to go ahead and close this issue, since I can't reproduce it. Please feel free to reopen if you figure out anything else.

**Closed by rchen152** 2020-08-11 18:47 UTC

**Comment by cihati** [comment] 2020-08-16 10:26
Sounds good. I wish I could create a smaller repro -- thanks a lot for your great work anyways!
