### ISSUE TITLE
Don't require .py extension

### ISSUE THREAD

**Issue by FRidh** [google/pytype#111] opened 2018-08-03 12:56 UTC
`pytype` refuses to operate on Python code that has no extension (as is typically done with executables).

**Comment by rchen152** [comment] 2018-08-07 19:29
This probably has something to do with importlab's (https://github.com/google/importlab) assumption in a few places that Python files have a ".py" extension - I'll take a look!

**Comment by gpshead** [comment] 2018-08-09 23:04
Related: we're introducing a `.py3` file extension internally in a few places where code for both 2 and 3 is different and needs to coexist.  Though that'll be more common within an occasional library than it will be for a main entry point file.  (a `.py3` when present takes priority over a potential `.py` file, only if being analyzed from a Python 3 perspective)

**Comment by martindemello** [comment] 2018-08-09 23:08
how does python's own import resolution mechanism handle files that don't end with .py?

**Comment by gpshead** [comment] 2018-08-10 00:03
It doesn't.  We've patched our python3 interpreter internally do accept py3 as a suffix (a relatively small change).  But the main file isn't actually imported so it doesn't have any name restrictions imposed by the interpreter.

**Comment by rchen152** [comment] 2018-09-29 00:36
Unfortunately, I haven't had time to look at this yet - unassigning myself because we have a fixit starting next week, and someone else may want to work on this.

**Comment by ritwik12** [comment] 2018-12-13 18:52
I can see that this issue is caused by https://github.com/google/importlab/blob/29a6ec92d3be80fce0edf019d769852e9fc71714/importlab/utils.py#L69

I would like to take this one. Please let me know.

**Comment by martindemello** [comment] 2018-12-13 18:59
that would be great! i'd be happy to do the code review.

now that importlab [handles unreadable files](https://github.com/google/importlab/blob/29a6ec92d3be80fce0edf019d769852e9fc71714/importlab/graph.py#L143) it might be enough just to remove the check for .py from `expand_source_files` and add a couple of tests to verify the behaviour for python and non-python files without an extension.

**Comment by rchen152** [comment] 2018-12-13 20:08
Thanks for taking this on! I think https://github.com/google/pytype/blob/master/pytype/tools/analyze_project/pytype_runner.py#L199 would also need to be changed to not filter out non-.py files.

**Comment by ritwik12** [comment] 2020-06-22 20:37
@rchen152 Isn't this issue resolved? What else is remaining here?

**Comment by rchen152** [comment] 2020-06-23 05:12
I probably just forgot to close it, thanks!

**Closed by rchen152** 2020-06-23 05:12 UTC
Labels: enhancement
