### ISSUE TITLE
asyncio.transports.Transport attribute-error set_write_buffer_limits

### ISSUE THREAD

**Issue by komuw** [google/pytype#350] opened 2019-06-22 12:54 UTC
```python
import asyncio

async def connect():
    writer: typing.Union[None, asyncio.streams.StreamWriter] = None
    _, writer = await asyncio.open_connection("google.com", "80")
    assert isinstance(writer, asyncio.streams.StreamWriter)
    writer.transport.set_write_buffer_limits(0)

loop = asyncio.get_event_loop()
loop.run_until_complete(connect())
```

`pytype --verbosity 0 --python-version 3.6 --protocols --strict-import --keep-going cool.py`

```bash
Computing dependencies
File "/cool.py", line 9, in connect: No attribute 'set_write_buffer_limits' on asyncio.transports.BaseTransport [attribute-error]
```

however that attribute exists
```python
>>> import asyncio
>>> asyncio.transports.Transport.set_write_buffer_limits
<function WriteTransport.set_write_buffer_limits at 0x10eff6e18>
>>>
```

**Comment by rchen152** [comment] 2019-06-24 22:45
Thanks for the report! The method will have to be added here: https://github.com/python/typeshed/blob/master/stdlib/3/asyncio/transports.pyi.

**Comment by rchen152** [comment] 2019-06-27 01:36
Turns out the method is already present - the issue is that set_write_buffer_limits is defined on asyncio.transports.WriteTransport (https://github.com/python/typeshed/blob/7e9e91cb7b281a9d6fff15b8ecde027c7195e257/stdlib/3/asyncio/transports.pyi#L16), but asyncio.streams.StreamWriter.transport has type asyncio.transports.BaseTransport (https://github.com/python/typeshed/blob/7e9e91cb7b281a9d6fff15b8ecde027c7195e257/stdlib/3/asyncio/streams.pyi#L88). I'm not sure if typeshed is wrong here or if StreamWriter.transport is not guaranteed to be a WriteTransport.

**Comment by komuw** [comment] 2019-06-27 02:31
okay, I see.
`StreamWriter.transport` has a general type to fake python interface-ness

It is a tricky thing to try and resolve at the pytype library level.   
I guess the question at the pytype level is; I would expect pytype to notice via `assert isinstance(writer, asyncio.streams.StreamWriter)`  that the writer in question is now actually a `StreamWriter` and hence its transport is now of the more specific type of `asyncio.transports.WriteTransport ` and thus has `set_write_buffer_limits`

**Comment by rchen152** [comment] 2019-06-27 23:22
I'm not sure why the assert would help? It says that the writer is a `StreamWriter`, but typeshed has the type of `StreamWriter.transport` as `BaseTransport` rather than `WriteTransport`.

**Comment by rchen152** [comment] 2021-01-11 09:42
I'm going to close this issue, since it doesn't appear to be a bug in pytype.

**Closed by rchen152** 2021-01-11 09:42 UTC
Labels: bug
