### ISSUE TITLE
2019.04.26 installation fails with "parser_ext.o: file not recognized"

### ISSUE THREAD

**Issue by infokiller** [google/pytype#305] opened 2019-05-05 10:57 UTC
I tried installing it in a clean python 3.6 environment created with conda but it fails with [these logs](https://gist.github.com/infokiller/b730abb0b20b785b3324851b85e65103).

**Comment by rchen152** [comment] 2019-05-06 20:28
Thanks for the report. Have you previously been able to install pytype using this setup, or has this been failing all along?

**Comment by infokiller** [comment] 2019-05-07 08:45
Yes, I've been able to install it on the same machine running archlinux.

**Comment by rchen152** [comment] 2019-05-09 06:34
Thanks for the additional information. Some googling turned up the very similar looking https://github.com/pytorch/pytorch/issues/16683, where someone had trouble installing PyTorch with conda. What worked for them was (quoting from the second comment):

> You can see that the build command (which caused my error) uses Anaconda's `ld` instead of system `ld` as it specifies `-B` option which points to Anaconda's folder:
> 
> ```shell
> g++ -pthread -shared -B /opt/anaconda/compiler_compat -L/opt/anaconda/lib -Wl,-rpath=/opt/anaconda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/torch/csrc/stub.o -L/home/manjaro/Downloads/pytorch/torch/lib -lshm -ltorch_python -o build/lib.linux-x86_64-3.7/torch/_C.cpython-37m-x86_64-linux-gnu.so -Wl,-rpath,$ORIGIN/lib
> ```
> 
> To fix my error I ran `python setup.py clean` and then I temporarily renamed Anaconda's `ld` linker to `ld-old` to make it _invisible_ during PyTorch installation. Removing `-B` option from the installation stage could fix it too.

Could you see if that helps?

**Comment by infokiller** [comment] 2019-05-09 10:57
Thanks @rchen152 this indeed fixed the issue!
I'm not sure if this issue is related to pytype or conda... I'll open another issue on conda and see what they say.

**Comment by rchen152** [comment] 2019-06-27 01:01
From the conda issue you opened, it looks like installation of an unrelated package failed with the same error (https://github.com/espnet/espnet/issues/879), so I'm going to go ahead and close this issue as likely not caused by pytype. Thanks for bringing it to our attention!

**Closed by rchen152** 2019-06-27 01:01 UTC
Labels: bug
