### ISSUE TITLE
No such file or directory: 'ninja'

### ISSUE THREAD

**Issue by dclong** [google/pytype#642] opened 2020-08-10 00:20 UTC
Running pytype on a Python scripts gives me the following error message. 
```
Computing dependencies
Analyzing 1 sources with 2 local dependencies
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workdir/user/chdu/side_projects/dbay/.venv/lib/python3.8/site-packages/pytype/__main__.py", line 10, in <module>
    sys.exit(main())
  File "/workdir/user/chdu/side_projects/dbay/.venv/lib/python3.8/site-packages/pytype/tools/analyze_project/main.py", line 97, in main
    return runner.run()
  File "/workdir/user/chdu/side_projects/dbay/.venv/lib/python3.8/site-packages/pytype/tools/analyze_project/pytype_runner.py", line 355, in run
    ret = self.build()
  File "/workdir/user/chdu/side_projects/dbay/.venv/lib/python3.8/site-packages/pytype/tools/analyze_project/pytype_runner.py", line 346, in build
    return subprocess.call(command)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja'
```

**Comment by rchen152** [comment] 2020-08-10 17:23
Thanks for the bug report. At a glance, it looks like `ninja` is not installed. Did you see any error messages about ninja while pytype was installing? Is ninja available outside of pytype? (You can check by running a command such as `ninja --version` or `which ninja` on the commandline.)

**Comment by dclong** [comment] 2020-08-10 19:03
That's what I thought and I did try to install `ninja` and it seems to be already installed. Not sure whether it was corrupted. Didn't try to force reinstall. Let me give it a try and get back to you.

**Comment by dclong** [comment] 2020-08-14 17:38
I confirm that this issue was due to ninja not available rather than pytype.

**Comment by dclong** [comment] 2020-08-18 00:11
Reopening this issue: 

As a matter of fact, is it possible for pytype to use Python API of ninja rather than the ninja command? In systems where users uses Python virtual environments, it can be quite tricky to get $PATH configured right especially when users work with multiple Python environments at the same time. If pytype uses the Python API of ninja, then configuring $PATH is less a problem.

**Comment by adamchainz** [comment] 2020-09-04 11:28
I have hit this bug too when using the path to my venv `pytype` executable without the venv activated:

```
$ python -m venv venv
$ source venv/bin/activate
$ pip install pytype
...
Successfully installed attrs-20.1.0 decorator-4.4.2 importlab-0.5.1 networkx-2.5 ninja-1.10.0.post1 pytype-2020.8.28 pyyaml-5.3.1 six-1.15.0 typed-ast-1.4.1
...
$ echo 1 > test.py
$ pytype test.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/Users/chainz/tmp/pytype-example/.pytype'
[1/1] check test
Success: no errors found
$ deactivate
$ ./venv/bin/pytype test.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
Traceback (most recent call last):
  File "./venv/bin/pytype", line 8, in <module>
    sys.exit(main())
  File "/Users/chainz/tmp/pytype-example/venv/lib/python3.8/site-packages/pytype/tools/analyze_project/main.py", line 97, in main
    return runner.run()
  File "/Users/chainz/tmp/pytype-example/venv/lib/python3.8/site-packages/pytype/tools/analyze_project/pytype_runner.py", line 362, in run
    ret = self.build()
  File "/Users/chainz/tmp/pytype-example/venv/lib/python3.8/site-packages/pytype/tools/analyze_project/pytype_runner.py", line 353, in build
    return subprocess.call(command)
  File "/Users/chainz/.pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/chainz/.pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/chainz/.pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja'
```

Using venv executables without the venv active is a common-enough usecase imo, useful for getting e.g. unrelated tools to run the program. The scripts in the `venv/bin` directory are given a shebang to run with the correct Python executable:

```
$ head ./venv/bin/pytype
#!/Users/chainz/tmp/pytype-example/venv/bin/python
```

However running `subprocess.call(["something'])` won't have the venv bin directory on the path. One coudl temporarily add it.

An alternative is to execute sub-commands with the equivalent of `python -m package` using the current interpreter: `subprocess.call([sys.executable, "-m", "package"])`. Unfortunately the Python `ninja` wrapper doesn't currently support `python -m ninja`, but there's an open issue: https://github.com/scikit-build/ninja-python-distributions/issues/36.

**Comment by nathanielmanistaatgoogle** [comment] 2020-09-07 15:24
I and a few other collaborators have also been hitting this in recent weeks.

I believe that steps to reproduce this are as easy as
```bash
temp-temp % python -m venv my_venv
temp-temp % ./my_venv/bin/pip install --upgrade pip pytype
  # <stuff gets installed>
temp-temp % mkdir lol
temp-temp % cd lol
lol % touch lol.py
lol % ../my_venv/bin/pytype .
Computing dependencies
Analyzing 1 sources with 0 local dependencies
Traceback (most recent call last):
  # <stack frames omitted>
FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'
```
. Might this be reopened? If it is reopened and if @jcfr's [ninja #37](https://github.com/scikit-build/ninja-python-distributions/pull/37) is integrated into `ninja` and [released](https://pypi.org/project/ninja/#history), would this issue become fixable according to what @adamchainz [described a few days ago](https://github.com/google/pytype/issues/642#issuecomment-687087052)?

**Comment by rchen152** [comment] 2020-09-08 18:38
Weird, I'll look into this.

**Comment by jcfr** [comment] 2020-09-08 18:52
> Might this be reopened? If it is reopened and if @jcfr's ninja #37 is integrated into ninja and released, would this issue become fixable according to what @adamchainz described a few days ago?

Thanks for the ping and for the suggestions. As soon as I am done integrating https://github.com/scikit-build/ninja-python-distributions/pull/37, I will create a new release of the wheel. 

I anticipate this will be completed before the end of the week.

Thanks for your patience

**Comment by rchen152** [comment] 2020-09-08 20:38
Summarizing the issue to the best of my understanding:

pytype does not support the following common workflow: create a virtualenv, pip install X, then run X **without activating the virtualenv**. To fix this, pytype needs to stop doing `subprocess.call(['ninja'])` and instead use `{path_to_venv_bin}/ninja` or `{path_to_venv_bin}/python -m ninja`. An additional wrinkle is that `python -m ninja` does not currently work due to scikit-build
/ninja-python-distributions/ninja not having a `__main__` file.

Once https://github.com/scikit-build/ninja-python-distributions/pull/37 is merged and released, https://github.com/google/pytype/commit/3cfc247147f4b4a8657d96e0c53862a9d2dc8708 appears to fix the issue. Even without that change to ninja-python-distribution, I think we could fix this by looking for a `ninja` executable in the same directory as the `pytype` executable, but that seems a little hackier, so if the ninja change will be rolled out this week, I'd prefer to wait for it.

@jcfr Thanks for all your work on ninja-python-distributions! One of the reasons we went with ninja for running pytype is how easy it is to install thanks to this project.

**Comment by adamchainz** [comment] 2020-09-08 21:52
Good summary! Yes waiting for ninja.__main__ seems sensible

**Comment by rchen152** [comment] 2020-09-14 23:10
Looks like the ninja change is merged and released! :D I'll try to close this issue out tomorrow.

**Closed** 2020-09-16 21:28 UTC
