### ISSUE TITLE
No attribute 'Type' on module 'google.cloud.spanner_v1' [module-attr]

### ISSUE THREAD

**Issue by dseomn** [google/pytype#1287] opened 2022-09-20 21:35 UTC
With pytype 2022.9.19 and google-cloud-spanner 3.21.0, I'm getting [this error](https://github.com/google/python-spanner-orm/actions/runs/3093571202/jobs/5006084468):

```
File "/home/runner/work/python-spanner-orm/python-spanner-orm/spanner_orm/table_apis.py", line 55, in <module>: No attribute 'Type' on module 'google.cloud.spanner_v1' [module-attr]
```

https://github.com/googleapis/python-spanner/blob/v3.21.0/google/cloud/spanner_v1/__init__.py imports `Type` on line 59 and includes it in `__all__` on line 135, so I think the attribute should exist.

**Comment by rchen152** [comment] 2022-09-22 04:25
When I look at the imports information that pytype's computed for table_apis.py, I see:
```
google/cloud/spanner_v1/transaction /usr/local/google/home/rechen/python-spanner-orm/.pytype/imports/default.pyi
```
So somehow the `from google.cloud import spanner_v1` import is just being ignored.

**Comment by rchen152** [comment] 2022-09-22 04:26
importlab is generating the right dependency tree, so that's not the issue:
```
$ importlab spanner_orm/table_apis.py --tree --trim
Reading 1 files
Source tree:
+ spanner_orm/table_apis.py
    :: logging/__init__.py
    :: typing.py
    :: google/cloud/spanner.py
    :: google/cloud/spanner_v1/__init__.py
    :: google/cloud/spanner_v1/transaction.py
```

**Comment by rchen152** [comment] 2022-09-22 04:39
Ohhh the problem is that typeshed has some google/cloud stubs: https://github.com/python/typeshed/tree/master/stubs/google-cloud-ndb. They're supposed to be for the google-cloud-ndb package, but pytype doesn't check whether a package is installed before using typeshed stubs. So it thinks that google/cloud/spanner_v1 is supposed to be in typeshed, but it's not.

**Comment by rchen152** [comment] 2022-09-22 06:13
Ha, seems like I made (and forgot) the same observation in https://github.com/google/pytype/issues/1081. I think I have a fix.

**Comment by rchen152** [comment] 2022-09-23 00:10
This was fixed by https://github.com/google/pytype/pull/1291, which will be in the next release (sometime next week).

**Closed by rchen152** 2022-09-23 00:10 UTC
Labels: bug, cat: infrastructure
