### ISSUE TITLE
int power operator bad-return-type

### ISSUE THREAD

**Issue by vinsonlee** [google/pytype#1349] opened 2023-01-11 20:53 UTC
```
def f(x: int) -> int:
    return x ** 2
```

```
f: bad option 'float' in return type [bad-return-type]
           Expected: int
  Actually returned: Union[float, int]
```

**Comment by rchen152** [comment] 2023-01-12 00:10
Thanks! This looks like a duplicate of https://github.com/google/pytype/issues/795.

**Closed by rchen152** 2023-01-12 00:10 UTC
