### ISSUE TITLE
Support for multiple files and following import statements?

### ISSUE THREAD

**Issue by levin-ilya** [google/pytype#65] opened 2017-09-20 21:41 UTC
I have 2 test files 'test.py' and 'utils.py' in the same directory. test.py imports from utils.py. 

1) Is it possible to let pytype to follow the imports from test.py? 
2) The help shows `pytype [options] file1.py[:file1.pyi] [file2.py:file2.pyi [...]]` which seems like I can pass more then one file. However when I run pytype utils.py test.py. I get `Can only process one file at a time.` Any I doing something wrong?
3) Does pytype work with entire projects (ie: type check entire directory)?

**Comment by matthiaskramm** [comment] 2017-09-20 21:47
The current approach is to do

```
pytype utils.py -o utils.pyi
```

and then

```
pytype test.py
```

We're planning a tool called "importlab" that can automate this process for you somewhat, especially when talking about entire directories.

**Comment by martindemello** [comment] 2018-02-06 23:17
Duplicate of #21

**Closed by martindemello** 2018-02-06 23:17 UTC
