### ISSUE TITLE
[import-error] on Travis-CI

### ISSUE THREAD

**Issue by Joe631** [google/pytype#441] opened 2019-10-24 15:48 UTC
I'm trying to add Pytype testing to our deployment process and am having trouble getting Pytype to find modules while running on Travis-CI (with or without tox).

Output from Travis:
```
$ source .tox/${TOX_ENV}/bin/activate && python --version && pip list && pytype -V 3.7

Python 3.7.1
/home/travis/build/myOrg/m-project/.tox/type/bin/python
Package          Version    

---------------- -----------

attrs            19.3.0     

certifi          2019.9.11  

chardet          3.0.4      

decorator        4.4.0      

myproject      0.1.0      

fastapi          0.38.1     

future           0.18.1     

idna             2.8        

importlab        0.5.1      

networkx         2.4        

ninja            1.9.0.post1

pip              18.1       

psycopg2         2.8.3      

pydantic         0.32.2     

PyHive           0.6.1      

python-dateutil  2.8.0      

pytype           2019.10.17 

PyYAML           5.1.2      

requests         2.22.0     

setuptools       40.5.0     

six              1.12.0     

SQLAlchemy       1.3.8      

SQLAlchemy-Utils 0.34.2     

starlette        0.12.8     

typed-ast        1.4.0      

urllib3          1.25.6     

wheel            0.32.2     

Computing dependencies

WARNING email-validator not installed, email fields will be treated as str.

To install, run: pip install email-validator

Analyzing 13 sources with 0 local dependencies

ninja: Entering directory `/home/travis/build/myOrg/my-project/pytype_output'

[1/8] check myproject.schemas

FAILED: /home/travis/build/myOrg/my-project/pytype_output/pyi/myproject/schemas.pyi 

pytype-single --disable pyi-error --imports_info /home/travis/build/myOrg/my-project/pytype_output/imports/myproject.schemas.imports --module-name myproject.schemas -V 3.7 -o /home/travis/build/myOrg/my-project/pytype_output/pyi/myproject/schemas.pyi --analyze-annotated --nofail --quick /home/travis/build/myOrg/my-project/myproject/schemas.py

File "/home/travis/build/myOrg/my-project/myproject/schemas.py", line 6, in <module>: Can't find module 'pydantic'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error.

ninja: build stopped: subcommand failed.

The command "source .tox/${TOX_ENV}/bin/activate && python --version && pip list && pytype -V 3.7" exited with 1.

Done. Your build exited with 1.
```

.travis.yaml
```
sudo: false
language: python

matrix:
  include:
    - python: 3.7
      env: TOX_ENV=type

before_install:
  - pip install pip==19.0

install:
    - pip install tox wheel


script:
    - tox -e type
    - source .tox/${TOX_ENV}/bin/activate && python --version && pip list && pytype -V 3.7
```

tox.ini
```
[tox]
envlist = type

[testenv]
deps =
    pytest
    pytype

install_command =
    python -m pip install {opts} {packages}


[testenv:type]
commands =
  pytype
deps =
  pytype
```

setup.py
```
from setuptools import setup, find_packages


setup(
    name='myproject',
    version='0.1.0',
    author='Data Science',
    description='DS API',
    install_requires=[
        "fastapi==0.38.1",
        "psycopg2==2.8.3",
        "pyhive==0.6.1",
        "sqlalchemy==1.3.8 ",
        "sqlalchemy_utils==0.34.2",
        "requests==2.22.0",
    ],
    packages=find_packages(exclude=['tests']),
    include_package_data=True
)
```

setup.cfg
```
[pytype]
inputs = myproject
exclude = tests
output = pytype_output
python_version = 3.7
pythonpath =.
disable = pyi-error
```

Pytype doesn't find any imported modules, installed or in my project, not just Pydantic.
This works locally with Tox.

**Comment by rchen152** [comment] 2019-11-01 04:30
Sorry for the slow response. One thing you could try is removing `pythonpath= .` from your pytype configuration, since that tells pytype to look for imports in the current directory (which I'm guessing isn't where pip-installed libraries are located), although I'm puzzled why the same configuration would work locally but not on Travis-CI.

**Comment by anentropic** [comment] 2020-03-04 17:09
I have the same problem

my travis config looks like:
```
# needed for python >= 3.6
sudo: required
dist: xenial
cache: pip
# ---
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
  - pip install .
script:
  # pytype does not work under 3.8 yet, and we only need to typecheck one 3.x version
  - if (( $(bc -l <<< "${TRAVIS_PYTHON_VERSION} == 3.7") )); then pytype -V 3.7 waterloo/; fi
  - pytest -v tests/
```
in the output I see:
```
$ pipenv install --dev --skip-lock
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile…
An error occurred while installing pytype! Will try again.
     ================================ 13/13 — 00:00:16
Installing initially failed dependencies…
     ================================ 1/1 — 00:00:17
$ pip install .
...
Requirement already satisfied: pydantic<1.5,>=1.4 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from waterloo==0.1.1) (1.4)
...
Successfully installed waterloo-0.1.1
$ if (( $(bc -l <<< "${TRAVIS_PYTHON_VERSION} == 3.7") )); then pytype -V 3.7 waterloo/; fi
Computing dependencies
Analyzing 16 sources with 0 local dependencies
ninja: Entering directory `/home/travis/build/anentropic/python-waterloo/.pytype'
[9/16] check waterloo.conf.__init__
FAILED: /home/travis/build/anentropic/python-waterloo/.pytype/pyi/waterloo/conf/__init__.pyi 
/home/travis/virtualenv/python3.7.1/bin/python -m pytype.single --imports_info /home/travis/build/anentropic/python-waterloo/.pytype/imports/waterloo.conf.__init__.imports --module-name waterloo.conf.__init__ -V 3.7 -o /home/travis/build/anentropic/python-waterloo/.pytype/pyi/waterloo/conf/__init__.pyi --analyze-annotated --nofail --quick /home/travis/build/anentropic/python-waterloo/waterloo/conf/__init__.py
File "/home/travis/build/anentropic/python-waterloo/waterloo/conf/__init__.py", line 5, in <module>: Can't find module 'pydantic'. [import-error]
```
In the following step, running the pytest tests, everything is fine so `pydantic` really is installed

Seems to be some problem with virtualenv/pipenv and pytype

based on https://github.com/google/pytype/issues/192 I added `-V 3.7` to the pytype command but it made no difference

For some reason I always see `An error occurred while installing pytype! Will try again.` in my builds followed by a retry and apparent success

**Comment by anentropic** [comment] 2020-03-04 23:04
FWIW this exact setup worked perfectly fine for me a few builds ago

it was only when I added `pydantic` dependency to my project that this error came up

I note the the OP also had a problem specifically with pydantic library

**Comment by rchen152** [comment] 2020-03-05 19:37
Oh, it's interesting that the `pydantic` library seems related to the problem in both cases. Thanks for noticing that.

**Comment by anentropic** [comment] 2020-05-17 18:10
Trying this in a different project...

Getting the same issue locally (not in Travis CI)

This time I'm using Poetry instead of pipenv

```
models.py", line 5, in <module>: Can't find module 'pydantic'. [import-error]
```

There's definitely something about Pydantic that trips up Pytype

**Comment by rchen152** [comment] 2021-01-15 03:58
A similar issue came up (https://github.com/google/pytype/issues/794), and I think I finally figured it out - the import errors were caused by our dependency finder ignoring .so files. The fix is in the latest version of https://pypi.org/project/importlab/ (0.6.1). The next release of pytype will require this version, but for now, you can manually upgrade the dependency.

**Closed by rchen152** 2021-01-15 03:58 UTC
Labels: bug
