### ISSUE TITLE
[pyi-error] for 'sqlalchemy.dialects.postgresql'

### ISSUE THREAD

**Issue by giulioindev** [google/pytype#1341] opened 2023-01-05 10:12 UTC
The error was raised for the following import line:

`from sqlalchemy.dialects.postgresql import JSON`

**Comment by rchen152** [comment] 2023-01-05 21:14
Thanks for the report! This looks like a duplicate of https://github.com/google/pytype/issues/1087.

**Closed by rchen152** 2023-01-05 21:14 UTC
