### ISSUE TITLE
mercurial.error gives pytype a sad

### ISSUE THREAD

**Issue by durin42** [google/pytype#22] opened 2016-05-31 23:29 UTC
~/Programming/pytype/env/bin/pytype mercurial/error.py
Traceback (most recent call last):
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 264, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 218, in main
    return _run_pytype(options)
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 258, in _run_pytype
    ret = process_one_file(input_filename, output_filename, options)
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 177, in process_one_file
    options=options)
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 86, in generate_pyi
    maximum_depth=(1 if options.quick else None))
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/infer.py", line 597, in infer_types
    ast = convert_structural.convert_pytd(ast, tracer.loader.concat_all())
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/convert_structural.py", line 243, in convert_pytd
    mapping, result = solve(ast, builtins_pytd)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/convert_structural.py", line 172, in solve
    return TypeSolver(ast, builtins_pytd).solve(), extract_local(ast)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/convert_structural.py", line 133, in solve
    self.match_unknown_against_complete(factory, solver, unknown, complete)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/convert_structural.py", line 61, in match_unknown_against_complete
    solver.implies(booleq.Eq(unknown.name, complete.name), implication)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/booleq.py", line 454, in implies
    assert e.right not in self.implications[e.left]
AssertionError

**Comment by matthiaskramm** [comment] 2016-06-07 21:08
Simplified down to

```
class LookupError(KeyError):
    def __init__(self, name, index, message):
      pass
```

which causes the same issue.

**Comment by alvarocaceres** [comment] 2016-07-21 18:03
Could not reproduce, with either "mercurial/error.py" or the pared-down version

**Comment by matthiaskramm** [comment] 2016-07-21 18:03
Right, this was fixed a while ago. Closing.

**Closed by matthiaskramm** 2016-07-21 18:03 UTC
