### ISSUE TITLE
Exhaustiveness checking with pytype

### ISSUE THREAD

**Issue by theahura** [google/pytype#1076] opened 2021-12-02 19:32 UTC
In mypy there is a technique to implement exhaustiveness checking using the NoReturn type. The short version is that you can create a 'magic' function like so:

```
def assert_never(value: NoReturn) -> NoReturn:
    assert False, f'Unhandled value: {value} ({type(value).__name__})'
```
and then call the magic function in an if block, e.g.:
```
from typing import Union

def get_float(num: Union[str, float]) -> float:
    if isinstance(num, str):
        return float(num)
    else:
        assert_never(num)
```
will throw a compile time error because it does not check the float type, while
```
def get_float(num: Union[str, float]) -> float:
    if isinstance(num, str):
        return float(num)

    elif isinstance(num, float):
        return num

    else:
        assert_never(num)
```
will not.

Does pytype support an equivalent?

See also: https://github.com/python/mypy/issues/5818

**Comment by rchen152** [comment] 2021-12-08 00:30
Interesting! Reading through python/mypy#5818, the variant that uses a custom class that nothing else can match (e.g.,
```
from typing import NoReturn
class Impossible: ...
def assert_never(value: Impossible) -> NoReturn: ...
```
) should work with pytype today. However, it does seem like both mypy and pyright are standardizing on the `(NoReturn) -> NoReturn` idiom, so perhaps we should support that, assuming PEP 484 is modified so that `NoReturn` as a parameter type is allowed.

**Comment by theahura** [comment] 2021-12-08 04:59
I wasn't able to get the Impossible class variant working. Here's an example of what I tried: 
```
from typing import NoReturn
import enum


class Impossible(enum.Enum):
  pass


def assert_never(x: Impossible) -> NoReturn:
  assert False, "Unhandled type: {}".format(type(x).__name__)


class InstanceType(Enum):
  IMAGE = 'IMAGE'
  WORDS = 'WORDS'


def _get_object_type_for_instance_type(
    instance_type: InstanceType) -> EndpointTypes:
  if instance_type is InstanceType.IMAGE:
    return EndpointTypes.IMAGE
  elif instance_type is InstanceType.WORDS:
    return EndpointTypes.WORDS
  else:
    assert_never(instance_type)
```

Even though `_get_object_type_for_instance_type` is exhaustive and instance_type _must_ fit one of the if branches before the final else is triggered, I get the following error:

```
FAILED: /home/soot/code/soot/api-server/.pytype/pyi/endpoints/v1/instances_utils.pyi 
/home/soot/code/soot/api-server/env/bin/python3 -m pytype.single --imports_info /home/soot/code/soot/api-server/.pytype/imports/endpoints.v1.instances_utils.imports --module-name endpoints.v1.instances_utils -V 3.8 -o /home/soot/code/soot/api-server/.pytype/pyi/endpoints/v1/instances_utils.pyi --analyze-annotated --nofail --quick /home/soot/code/soot/api-server/src/endpoints/v1/instances_utils.py
File "/home/soot/code/soot/api-server/src/endpoints/v1/instances_utils.py", line 73, in _get_object_type_for_instance_type: Function assert_never was called with the wrong arguments [wrong-arg-types]
         Expected: (x: Impossible)
  Actually passed: (x: InstanceType)
File "/home/soot/code/soot/api-server/src/endpoints/v1/instances_utils.py", line 73, in _get_object_type_for_instance_type: bad return type [bad-return-type]
           Expected: endpoints.v1.endpoint_types.EndpointTypes
  Actually returned: None

For more details, see https://google.github.io/pytype/errors.html
```

**Comment by rchen152** [comment] 2021-12-09 01:32
Ah, that's a bug specific to enums. The assert_never seems to be doing what it's supposed to; the problem is that pytype doesn't realize that the first two branches match all possible enum values.

**Comment by theahura** [comment] 2021-12-09 01:41
Gotcha. Is this something that is easy to fix? We use a lot of enums 😅 or do you have any thoughts on a good alternative?

**Comment by rchen152** [comment] 2021-12-10 05:13
No good alternatives are coming to mind, unfortunately - sorry to not be more helpful.

@Solumin Do you have any thoughts on if this is something that would be possible to support in the enum overlay?

**Comment by Solumin** [comment] 2021-12-10 19:00
It's a feature I'd really love to have, and there's very good reasons to implement it. I haven't spent too much time thinking about it, and I don't know what it would take to implement it. It's essentially extra-strength if-splitting, so it might require tackling the pile of if-splitting bugs.

**Comment by rchen152** [comment] 2022-10-27 23:05
We have exhaustiveness checking for enums now, but only in `match` statements. We don't currently have any plans to extend it to if/elif/else, although we're open to doing so if a use case comes up that can't be addressed by switching to `match`.

**Closed by rchen152** 2022-10-27 23:05 UTC
Labels: enhancement, cat: control flow

**Comment by theahura** [comment] 2022-10-29 18:13
the best reason I can think of is that not everyone is on Py 3.10, and Pytype's requirements actually state Python 3.7-3.9 :sweat_smile: unless I'm missing something, and earlier versions of python also support `match`? 
(also when I was at Google (granted, this was a year+ ago) most folks still hadn't moved off 3.8 :joy: )

**Comment by rchen152** [comment] 2022-11-01 00:36
Ah, pytype's README is out-of-date, sorry! We've supported 3.10 for a few months.

**Comment by theahura** [comment] 2022-11-01 01:00
Darn, was really hoping that would work 😂 I'm still on 3.8, and likely will be for a while (I suspect a lot of libraries were using aren't supporting 3.10 yet)
